// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        uuid.UUID
	Password  string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Room struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	MaxMembers  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMember struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RoomMessage struct {
	ID           uuid.UUID
	RoomID       uuid.UUID
	RoomMemberID uuid.UUID
	UserID       uuid.UUID
	Content      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
